# use resourceClasses for precise control:

prettyPrint: true
cacheTTL: 0
readAllResources: true  # Changed to false for more control
openAPI:
  info:
    version: '1.0'
    title: Stemmarest API
    description: 'API documentation for the Stammarest REST API'
    contact:
      email: renato.diaz@unil.ch
    license:
      name: MIT License
      url: https://opensource.org/license/mit/
  servers:
    - url: http://localhost:8080/stemmarest/api
      description: Development server